theme: jekyll-theme-midnight

title: Climate Economics
description: Economic analysis of climate, climate change, and climate policy

enable_google_verification: true  # enables google site verification
google_site_verification: GT-NSKZVTX # your google-site-verification ID (Google Search Console) 

tags:
- climate economics
- Richard Tol
- textbook

DNS: _github-challenge-ClimateEconomics-org.rtol 

